# Generated by Django 6.0.6 on 2026-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rejissor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='main.actor', verbose_name='Actors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rejissor',
            field=models.ManyToManyField(blank=True, to='main.rejissor', verbose_name='Rejissor'),
        ),
    ]
